Caught exception in thrower
Finally in thrower
Finally in main
Finally in thrower
Caught exception in main
Finally in main
